[lint]

preview = true

select = [
    "T",
    "Q",
    "W",
    "B",
    "N",
    "F",
    "FA",
    "RET",
    "PTH",
    "ERA",
    "PLW",
    "PERF",
    "RUF",
    "FLY",
    "PT",
    "PYI",
    "PIE",
    "ICN",
    "UP",
    "TRY",
    "C4",
    "E401",
    "E713",
    "E721",
    "S101",
    "S113",
    "SIM103",
    "SIM114",
    "SIM118",
    "SIM210",
    "PLR5501",
    "PLR1711",
]

ignore = [
    "PLW0108",
]

exclude = [
    "tests.py",
]